name: covid_19_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
   sdk: '>=2.1.0 <3.0.0'

dependencies:
   flutter:
      sdk: flutter
   flutter_sparkline: ^0.1.0
   cupertino_icons: ^0.1.2
   font_awesome_flutter: ^8.8.1
   http: ^0.12.0+4
   provider: ^4.0.5
   intl: ^0.16.1

dev_dependencies:
   flutter_test:
      sdk: flutter

flutter:
   uses-material-design: true

   assets:
      - assets/images/

   fonts:
      - family: Proxima
        fonts:
           - asset: fonts/Proxima-Nova-Regular.otf
           - asset: fonts/Proxima-Nova-Bold.otf
             weight: 700
